application: playhangmanonline
version: 3
runtime: python
api_version: 1

handlers:
- url: /js
  static_dir: js
- url: /css
  static_dir: css
 
- url: .*
  script: main.py

inbound_services:
- xmpp_message

builtins:
- remote_api: on
- datastore_admin: on